### ISSUE TITLE
crash in inner_wrapper(): AttributeError: 'NoneType' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by ktdreyer** [ceph/chacractl#33]
I'm seeing the following exception with chacractl 0.0.14:

```
calamari_1.5.5-2redhat1trusty.dsc | /home/jenkins-build/build/workspace/build-package-dist/ARCH/amd64/DIST/trusty/venv/bin/chacractl binary create /calamari/1.5.5-2redhat1trusty/ubuntu/all/source
[chacractl.api.binaries][INFO  ] reading input from stdin
[requests.packages.urllib3.connectionpool][DEBUG ] Starting new HTTPS connection (1): ubuntu-ceph-test.example.com
/home/jenkins-build/build/workspace/build-package-dist/ARCH/amd64/DIST/trusty/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/jenkins-build/build/workspace/build-package-dist/ARCH/amd64/DIST/trusty/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/build-package-dist/ARCH/amd64/DIST/trusty/venv/bin/chacractl", line 6, in <module>
    main.ChacraCtl()
  File "/home/jenkins-build/build/workspace/build-package-dist/ARCH/amd64/DIST/trusty/venv/local/lib/python2.7/site-packages/chacractl/main.py", line 38, in __init__
    self.main(argv)
  File "/home/jenkins-build/build/workspace/build-package-dist/ARCH/amd64/DIST/trusty/venv/local/lib/python2.7/site-packages/chacractl/decorators.py", line 68, in newfunc
    return f(*a, **kw)
  File "/home/jenkins-build/build/workspace/build-package-dist/ARCH/amd64/DIST/trusty/venv/local/lib/python2.7/site-packages/chacractl/main.py", line 82, in main
    parser.dispatch()
  File "/home/jenkins-build/build/workspace/build-package-dist/ARCH/amd64/DIST/trusty/venv/local/lib/python2.7/site-packages/tambo/dispatcher.py", line 21, in dispatch
    return instance.main()
  File "/home/jenkins-build/build/workspace/build-package-dist/ARCH/amd64/DIST/trusty/venv/local/lib/python2.7/site-packages/chacractl/api/binaries.py", line 172, in main
    self.post(url, filename)
  File "/home/jenkins-build/build/workspace/build-package-dist/ARCH/amd64/DIST/trusty/venv/local/lib/python2.7/site-packages/chacractl/util.py", line 75, in inner_wrapper
    status = e.response.status_code
AttributeError: 'NoneType' object has no attribute 'status_code'
```

**Comment by alfredodeza** [comment]
Fixed with 4bdc9acab321cc05d94995f2b28b576dfca1f94d

Will close once I get a release out

**Comment by alfredodeza** [comment]
Release 0.0.15 with the fix

**Comment by ktdreyer** [comment]
Cool, thank you!

For the record this crash was happening because `requests.head()` raised an `requests.exceptions.SSLError` (the Jenkins UID was unable to read the local CA certificate store file). In this case there was no HTTP response, which is why `e.response` was `None` here.
