### ISSUE TITLE
crash with ImportError: No module named OpenSSL.SSL

### ISSUE THREAD

**Issue by alfredodeza** [ceph/chacractl#41]
With a new release of `requests_toolbelt` (0.9.0) it broke the tool because `pyopenssl` is no longer being installed as a dependency (or not declared?):

    Traceback (most recent call last):
      File "/tmp/venv.yCivgF8IPC/bin/chacractl", line 3, in <module>
        from chacractl import main
      File "/tmp/venv.yCivgF8IPC/local/lib/python2.7/site-packages/chacractl/main.py", line 7, in <module>
        from chacractl.api import binaries, repos, exists, projects
      File "/tmp/venv.yCivgF8IPC/local/lib/python2.7/site-packages/chacractl/api/binaries.py", line 12, in <module>
        from requests_toolbelt.multipart.encoder import MultipartEncoder
      File "/tmp/venv.yCivgF8IPC/local/lib/python2.7/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
        from .adapters import SSLAdapter, SourceAddressAdapter
      File "/tmp/venv.yCivgF8IPC/local/lib/python2.7/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
        from .ssl import SSLAdapter
      File "/tmp/venv.yCivgF8IPC/local/lib/python2.7/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
        from .._compat import poolmanager
      File "/tmp/venv.yCivgF8IPC/local/lib/python2.7/site-packages/requests_toolbelt/_compat.py", line 59, in <module>
        from urllib3.contrib.pyopenssl import PyOpenSSLContext
      File "/tmp/venv.yCivgF8IPC/local/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
        import OpenSSL.SSL
    ImportError: No module named OpenSSL.SSL

Tracking upstream issue at:

https://github.com/requests/toolbelt/issues/241

**Comment by alfredodeza** [comment]
The current fix for this is to just install `pyopenssl` but the `requests_toolbelt` team has a better patch not to include it.

Once that is out, we should pin `requests_toolbelt` to that version

**Comment by alfredodeza** [comment]
Fixed with 68c7c670629e121291e1287cb05acc880f7c8d01

A separate issue will have to be open to track down the new version of requests-toolbelt, so that it can be pinned
